version: "3"

services:

  node:
    container_name: 'remix-node'
    build: './web'
    ports:
      - 80:3000
      - 81:3001
      - 8080:8080
    tty: true
    volumes:
      - ./web/:/myapp:rw
      - ./web/node_modules:/myapp/node_modules:cached
    working_dir: /myapp
    environment:
      HOST: 0.0.0.0
    #command: bash -c 'yarn install && yarn run dev'